### PR TITLE
Update Composer

### PR DESCRIPTION
**Pull request by misfist**
Removed Kale theme
Removed colormag theme
Added .ssh path to authenticate
Ignore project file
Fixed syntax error

### CODE REVIEW

**Comment by misfist** [comment]
@emhoracek - I got a new laptop with Linux and have Trellis working!!

**Comment by emhoracek** [comment]
@misfist That is awesome!!! 🐧 How's it working? What do you think?

**Comment by misfist** [comment]
Just did my first deploy. Once you have everything working, it's pretty cool.

**Comment by misfist** [comment]
Yippee! I have it working on my MacBook now too. It's side-by-side with my [VVV](https://varyingvagrantvagrants.org/) set-up. I think re-installing Ansible was maybe what did it.

**Comment by misfist** [comment]
Should be integrated into https://github.com/positiondev/tni-wordpress/pull/5

**Pull request closed without merging**
